// AUTHORIZATON & AUTHENTICATION
export const AUTH_USER = 'AUTH_USER'
export const CLEAR_AUTH_DATA = 'CLEAR_AUTH_DATA'
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR'
export const AUTH_ERROR = 'AUTH_ERROR'
export const STORE_USER = 'STORE_USER'

// VESSELS
export const FETCHING_VESSEL = 'FETCHING_VESSEL'
export const STORE_VESSEL = 'STORE_VESSEL'
export const DELETE_VESSEL = 'DELETE_VESSEL'

// REPORTS
export const FETCHING_REPORTS = 'FETCHING_REPORTS'
export const STORE_REPORTS = 'STORE_REPORTS'
export const ADD_REPORT = 'ADD_REPORT'
export const DELETE_REPORT = 'DELETE_REPORT'

export const SIDEBAR_VISIBLE = 'SIDEBAR_VISIBLE'
export const SELECTED_VESSEL_DETAILS_COMPONENT = 'SELECTED_VESSEL_DETAILS_COMPONENT'
