export default {
  COLOR_POINT: '#F37272',
  COLOR_POINT_FILL: '#FFF',
  COLOR_LANDSCAPE: '#FFF',
  COLOR_WATER: '#C3E6FF',
  COLOR_LINE: '#FFF',
  COLOR_SELECTED_POINT: '#00b853',
  COLOR_BROWN: '#8B4513',
  COLOR_BLACK: '#000',
  COLOR_BLUE: '#4d6d9b'
};
